FROM flowable/flowable-ui AS flowable-ui
ENTRYPOINT ["docker run -p8080:8080 flowable/flowable-rest"]

FROM flowable/flowable-rest AS flowable-rest
ENTRYPOINT ["docker run -p8081:8080 flowable/flowable-rest"]